import password_generator as pg
import logging
users = []
passwords = []
logging.basicConfig(filename="login_system_log.log", level=logging.INFO, format="%(asctime)s:%(levelname)s:%(message)s")
log = logging.getLogger(__name__)

def gen_login():
    user_name = input("Please enter your username")
    log.info("User name is inputted by user to system. User : {}".format(user_name))
    if user_name in users:
        log.debug("Checking if user name has been used before")
        print("That username is already taken, please try again")
        log.info("Username is taken so they need to retry")
        gen_login()
    else:
        users.append(user_name)
        log.debug("Adding the user to the database.")
        want_password = input("Do you want us to generate a password for you, yes or no?")
        log.debug("Asking if the user wants a auto-generated password.")
        if want_password == "yes":
            password = pg.create_password()
            print(password)
            print("Your password is {}".format(password))
            log.info("The password as been autogenerated to: {}.".format(password))
        else:
            password = input("Please enter your password")
            print("Your password is {}".format(password))
            log.info("User decided to create their own password")
        passwords.append(password)
    print("Thank you for registering, your username is: ({}) and your password is: ({})!".format(user_name, password))

gen_login()